{% set name = "esi-utils-vectors" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esi-utils-vectors-{{ version }}.tar.gz
  sha256: 011238b8c6e8f5921afb119f433649571e01c5c951c3dca046afbc97b9c467ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - esi-extern-openquake >=1.0.0
    - numpy >=1.21

test:
  imports:
    - esi_utils_vectors
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://code.usgs.gov/ghsc/esi/esi-utils-vectors
  summary: USGS Earthquake Impact Utilities for Vectors
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
